### ISSUE TITLE
Read LOG freezes app and flipper needs to be restarted

### ISSUE THREAD

**Issue by throughthetrees** [ElectronicCats/flipper-rs485modbus#7]
when you clock `Read LOG` in the app it freezes/ crashes the app, and you need to restart the flipper.

**Comment by Marcelol52** [comment]
Hi @throughthetrees, thank you for sharing this with us. We will try to replicate your issue and find a solution for it. Please share as much details as you can of what you were doing when you encountered the problem.

**Comment by sabas1080** [comment]
Hi @throughthetrees fixed in #9 , now in release, thanks for you feedback
